apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: loj4jxuuc-nodejs 
  janus-idp.io/tekton: loj4jxuuc-nodejs
  backstage.io/kubernetes-id: loj4jxuuc-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: loj4jxuuc-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml